# This notebooks was used to understand the dataset and understand the data structure and how to use it.

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
data = pd.read_csv("../../data/eyes-dataset/Training_Set/Training_Set/RFMiD_Training_Labels.csv",
                 sep=",",
                 header=0)
data

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915,1916,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1916,1917,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1917,1918,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1918,1919,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1919,1920,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
print(data.columns[1:])

Index(['Disease_Risk', 'DR', 'ARMD', 'MH', 'DN', 'MYA', 'BRVO', 'TSLN', 'ERM',
       'LS', 'MS', 'CSR', 'ODC', 'CRVO', 'TV', 'AH', 'ODP', 'ODE', 'ST',
       'AION', 'PT', 'RT', 'RS', 'CRS', 'EDN', 'RPEC', 'MHL', 'RP', 'CWS',
       'CB', 'ODPM', 'PRH', 'MNF', 'HR', 'CRAO', 'TD', 'CME', 'PTCR', 'CF',
       'VH', 'MCA', 'VS', 'BRAO', 'PLQ', 'HPED', 'CL'],
      dtype='object')

In [4]:
# creation d'un dossier pour chaque maladie

In [5]:
for title in data.columns[1:]:
    if not os.path.exists(f'{title}'):
        os.mkdir(f'../../data/eyes-dataset/Sort/{title}')
        print(f"Created folder '{title}'.")
    else:
        print(f"Folder '{title}' already exists.")

Created folder 'Disease_Risk'.
Created folder 'DR'.
Created folder 'ARMD'.
Created folder 'MH'.
Created folder 'DN'.
Created folder 'MYA'.
Created folder 'BRVO'.
Created folder 'TSLN'.
Created folder 'ERM'.
Created folder 'LS'.
Created folder 'MS'.
Created folder 'CSR'.
Created folder 'ODC'.
Created folder 'CRVO'.
Created folder 'TV'.
Created folder 'AH'.
Created folder 'ODP'.
Created folder 'ODE'.
Created folder 'ST'.
Created folder 'AION'.
Created folder 'PT'.
Created folder 'RT'.
Created folder 'RS'.
Created folder 'CRS'.
Created folder 'EDN'.
Created folder 'RPEC'.
Created folder 'MHL'.
Created folder 'RP'.
Created folder 'CWS'.
Created folder 'CB'.
Created folder 'ODPM'.
Created folder 'PRH'.
Created folder 'MNF'.
Created folder 'HR'.
Created folder 'CRAO'.
Created folder 'TD'.
Created folder 'CME'.
Created folder 'PTCR'.
Created folder 'CF'.
Created folder 'VH'.
Created folder 'MCA'.
Created folder 'VS'.
Created folder 'BRAO'.
Created folder 'PLQ'.
Created folder 'HPED'.
Created folder 'CL'.

In [6]:
# c/p de chaque image de training_set dans son bon dossier
import shutil

In [7]:
data.info

<bound method DataFrame.info of         ID  Disease_Risk  DR  ARMD  MH  DN  MYA  BRVO  TSLN  ERM  ...  CME  \
0        1             1   1     0   0   0    0     0     0    0  ...    0
1        2             1   1     0   0   0    0     0     0    0  ...    0
2        3             1   1     0   0   0    0     0     0    0  ...    0
3        4             1   0     0   1   0    0     0     0    0  ...    0
4        5             1   1     0   0   0    0     0     0    0  ...    0
...    ...           ...  ..   ...  ..  ..  ...   ...   ...  ...  ...  ...
1915  1916             1   0     0   0   0    0     0     0    0  ...    0
1916  1917             1   1     0   0   0    0     0     0    0  ...    0
1917  1918             0   0     0   0   0    0     0     0    0  ...    0
1918  1919             0   0     0   0   0    0     0     0    0  ...    0
1919  1920             0   0     0   0   0    0     0     0    0  ...    0

      PTCR  CF  VH  MCA  VS  BRAO  PLQ  HPED  CL
0        0   0   0    0   0     0    0     0   0
1        0   0   0    0   0     0    0     0   0
2        0   0   0    0   0     0    0     0   0
3        0   0   0    0   0     0    0     0   0
4        0   0   0    0   0     0    0     0   0
...    ...  ..  ..  ...  ..   ...  ...   ...  ..
1915     0   0   0    0   0     0    0     0   0
1916     0   0   0    0   0     0    0     0   0
1917     0   0   0    0   0     0    0     0   0
1918     0   0   0    0   0     0    0     0   0
1919     0   0   0    0   0     0    0     0   0

[1920 rows x 47 columns]>

In [8]:
data[2:3]

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data[1919:1920]['Disease_Risk'].item()

0

In [11]:
data[1919:1920]['Disease_Risk']

1919    0
Name: Disease_Risk, dtype: int64

In [12]:
for title in data.columns[1:]:
    for i in range(1919):
        if data[i:i+1][title].item() == 1:
            shutil.copyfile(r'C:\Data\Projet CODE\Code Python\DataCamp Code\data\eyes-dataset\Training_Set\Training_Set\Training\{}.png'.format(i+1),
                           r'C:\Data\Projet CODE\Code Python\DataCamp Code\data\eyes-dataset\Sort\{}\{}.png'.format(title, i+1))

In [13]:
for title in data.columns[1:]:
    print(f'{title} : {data[title].sum()}')

Disease_Risk : 1519
DR : 376
ARMD : 100
MH : 317
DN : 138
MYA : 101
BRVO : 73
TSLN : 186
ERM : 14
LS : 47
MS : 15
CSR : 37
ODC : 282
CRVO : 28
TV : 6
AH : 16
ODP : 65
ODE : 58
ST : 5
AION : 17
PT : 11
RT : 14
RS : 43
CRS : 32
EDN : 15
RPEC : 22
MHL : 11
RP : 6
CWS : 3
CB : 1
ODPM : 0
PRH : 2
MNF : 3
HR : 0
CRAO : 2
TD : 3
CME : 4
PTCR : 5
CF : 3
VH : 1
MCA : 1
VS : 1
BRAO : 2
PLQ : 1
HPED : 1
CL : 1

In [56]:
# c/p de chaque image de test_set dans son bon dossier (added 1920)
data_test = pd.read_csv("DataSet/Test_Set/Test_Set/RFMiD_Testing_Labels.csv",
                 sep=",",
                 header=0)
data_test

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
636,637,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
637,638,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
638,639,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
639,640,1,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [57]:
for title in data_test.columns[1:]:
    for i in range(639):
        if data_test[i:i+1][title].item() == 1:
            shutil.copyfile(r'DataSet/Test_Set/Test_Set/Test/{}.png'.format(i+1),
                           r'thedataset/{}/{}.png'.format(title, i+1+1920))

In [58]:
for title in data_test.columns[1:]:
    print(f'{title} : {data_test[title].sum() + data[title].sum()}')

Disease_Risk : 2025
DR : 500
ARMD : 131
MH : 421
DN : 184
MYA : 133
BRVO : 96
TSLN : 239
ERM : 19
LS : 62
MS : 22
CSR : 50
ODC : 373
CRVO : 37
TV : 8
AH : 21
ODP : 89
ODE : 75
ST : 7
AION : 21
PT : 15
RT : 19
RS : 57
CRS : 43
EDN : 19
RPEC : 26
MHL : 14
RP : 8
CWS : 5
CB : 2
ODPM : 0
PRH : 4
MNF : 3
HR : 1
CRAO : 2
TD : 7
CME : 6
PTCR : 5
CF : 4
VH : 2
MCA : 1
VS : 1
BRAO : 2
PLQ : 1
HPED : 1
CL : 2

In [59]:
# c/p de chaque image de evaluation_set dans son bon dossier (added 1920+640)
data_eval = pd.read_csv("DataSet/Evaluation_Set/Evaluation_Set/RFMiD_Validation_Labels.csv",
                 sep=",",
                 header=0)
data_eval

,ID,Disease_Risk,DR,ARMD,MH,DN,MYA,BRVO,TSLN,ERM,...,CME,PTCR,CF,VH,MCA,VS,BRAO,PLQ,HPED,CL
0,1,1,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635,636,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
636,637,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
637,638,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
638,639,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
639,640,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
for title in data_eval.columns[1:]:
    for i in range(639):
        if data_eval[i:i+1][title].item() == 1:
            shutil.copyfile(r'DataSet/Evaluation_Set/Evaluation_Set/Validation/{}.png'.format(i+1),
                           r'thedataset/{}/{}.png'.format(title, i+1+1920+640))

In [61]:
for title in data.columns[1:]:
    print(f'{title} : {data_test[title].sum() + data[title].sum() + data_eval[title].sum()}')

Disease_Risk : 2531
DR : 632
ARMD : 169
MH : 523
DN : 230
MYA : 167
BRVO : 119
TSLN : 304
ERM : 26
LS : 79
MS : 27
CSR : 61
ODC : 445
CRVO : 45
TV : 10
AH : 25
ODP : 115
ODE : 96
ST : 11
AION : 26
PT : 17
RT : 25
RS : 71
CRS : 54
EDN : 24
RPEC : 32
MHL : 17
RP : 10
CWS : 8
CB : 2
ODPM : 2
PRH : 5
MNF : 3
HR : 1
CRAO : 4
TD : 9
CME : 7
PTCR : 6
CF : 6
VH : 4
MCA : 1
VS : 4
BRAO : 4
PLQ : 2
HPED : 1
CL : 2

In [65]:
print(data_test['Disease_Risk' ].sum() + data['Disease_Risk' ].sum() + data_eval['Disease_Risk' ].sum())

2531

In [14]:
# here we add the healthy eyes
for i in range(1919):
    if data[i:i+1]['Disease_Risk'].item() == 0:
        shutil.copyfile(r'C:\Data\Projet CODE\Code Python\DataCamp Code\data\eyes-dataset\Training_Set\Training_Set\Training\{}.png'.format(i+1),
                      r'C:\Data\Projet CODE\Code Python\DataCamp Code\data\eyes-dataset\Sort\healthy\{}.png'.format(i+1))
            
# for i in range(639):
#     if data_test[i:i+1]['Disease_Risk'].item() == 0:
#         shutil.copyfile(r'DataSet/Test_Set/Test_Set/Test/{}.png'.format(i+1),
#                        r'thedataset/healthy/{}.png'.format(i+1+1920))
#             
# for i in range(639):
#     if data_eval[i:i+1]['Disease_Risk'].item() == 0:
#         shutil.copyfile(r'DataSet/Evaluation_Set/Evaluation_Set/Validation/{}.png'.format(i+1),
#                        r'thedataset/healthy/{}.png'.format(i+1+1920+640))